on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build_tsan_reusable:
    name: 'Thread sanitizer (free-threading)'
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Runner image version
      run: echo "IMAGE_VERSION=${ImageVersion}" >> $GITHUB_ENV
    - name: Restore config.cache
      uses: actions/cache@v4
      with:
        path: config.cache
        key: ${{ github.job }}-${{ runner.os }}-${{ env.IMAGE_VERSION }}-${{ hashFiles('configure', 'configure.ac', '.github/workflows/build.yml') }}
    - name: Install Dependencies
      run: |
        sudo ./.github/workflows/posix-deps-apt.sh
        # Install clang-18
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 17  # gh-121946: llvm-18 package is temporarily broken
        sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-17 100
        sudo update-alternatives --set clang /usr/bin/clang-17
        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-17 100
        sudo update-alternatives --set clang++ /usr/bin/clang++-17
        # Reduce ASLR to avoid TSAN crashing
        sudo sysctl -w vm.mmap_rnd_bits=28
    - name: TSAN Option Setup
      run: |
        echo "TSAN_OPTIONS=log_path=${GITHUB_WORKSPACE}/tsan_log suppressions=${GITHUB_WORKSPACE}/Tools/tsan/suppressions_free_threading.txt handle_segv=0" >> $GITHUB_ENV
        echo "CC=clang" >> $GITHUB_ENV
        echo "CXX=clang++" >> $GITHUB_ENV
    - name: Add ccache to PATH
      run: |
        echo "PATH=/usr/lib/ccache:$PATH" >> $GITHUB_ENV
    - name: Configure ccache action
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        save: ${{ github.event_name == 'push' }}
        max-size: "200M"
    - name: Configure CPython
      run: ./configure --config-cache --disable-gil --with-thread-sanitizer --with-pydebug
    - name: Build CPython
      run: make -j4
    - name: Display build info
      run: make pythoninfo
    - name: Install requests
      run: |
        ./python -m ensurepip
        ./python -m pip install "requests>=2.30.0"
    - name: Tests
      run: |
        sudo mkdir -p /cores
        sudo chmod 777 /cores
        sudo bash -c 'echo "/cores/%e.%p.%t" > /proc/sys/kernel/core_pattern'
        ulimit -c unlimited
        ./python -E -u -X dev -X warn_default_encoding -Werror ./test_requests_crasher.py
    - name: Display TSAN logs
      if: always()
      run: find ${GITHUB_WORKSPACE} -name 'tsan_log.*' | xargs head -n 1000
    - name: Archive TSAN logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: tsan-logs-free-threading
        path: tsan_log.*
        if-no-files-found: ignore
